// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BuildingLink.ModuleServiceTemplate.Repositories.DatabaseFirst.Users
{
    [Table("PermissionSetting")]
    [Index(nameof(PermissionId), nameof(SubTypeId), nameof(BuildingTypeId), nameof(ManagingAgencyId), nameof(BuildingId), nameof(PhysicalUnitId), nameof(OccupancyId), nameof(UserId), Name = "missing_index_288493")]
    [Index(nameof(PermissionId), nameof(OptionId), Name = "missing_index_754562")]
    [Index(nameof(PermissionId), nameof(OptionId), Name = "missing_index_755827")]
    public partial class PermissionSetting
    {
        [Key]
        public short PermissionId { get; set; }
        [Key]
        public int BuildingTypeId { get; set; }
        [Key]
        public int ManagingAgencyId { get; set; }
        [Key]
        public int BuildingId { get; set; }
        [Key]
        public int UserTypeId { get; set; }
        [Key]
        public int PhysicalUnitId { get; set; }
        [Key]
        public int OccupancyId { get; set; }
        [Key]
        public int UserId { get; set; }
        [Key]
        public int SubTypeId { get; set; }
        public short OptionId { get; set; }
        [Column("CreateDateUTC", TypeName = "datetime")]
        public DateTime CreatedDate{ get; set; }
        [Column("CreateUserId")]
        public int CreatedUserId { get; set; }
        [Column("ChangeDateUTC", TypeName = "datetime")]
        public DateTime ChangedDate { get; set; }
        public int ChangeUserId { get; set; }

        [ForeignKey(nameof(CreatedUserId))]
        public virtual User CreatedUser { get; set; }
        [ForeignKey(nameof(SubTypeId))]
        public virtual UserSubType SubType { get; set; }
        [ForeignKey(nameof(UserId))]
        public virtual User User { get; set; }
    }
}