// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BuildingLink.ModuleServiceTemplate.Repositories.DatabaseFirst.Users
{
    public partial class UserPermissionSetting
    {
        public short PermissionId { get; set; }
        public int BuildingTypeId { get; set; }
        public int ManagingAgencyId { get; set; }
        public int BuildingId { get; set; }
        public int UserTypeId { get; set; }
        public int PhysicalUnitId { get; set; }
        public int OccupancyId { get; set; }
        public int UserId { get; set; }
        public short OptionId { get; set; }
        public DateTime CreateDateUTC { get; set; }
        public DateTime ChangeDateUTC { get; set; }
        public int CreateUserId { get; set; }
        public int ChangeUserId { get; set; }
        public int SubTypeId { get; set; }
    }
}
