// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BuildingLink.ModuleServiceTemplate.Repositories.DatabaseFirst.Users
{
    [Table("UserSubType")]
    public partial class UserSubType
    {
        public UserSubType()
        {
            InverseParent = new HashSet<UserSubType>();
            TblUsers = new HashSet<User>();
        }

        [Key]
        public int Id { get; set; }
        public int? ParentId { get; set; }
        public short? NodeLevel { get; set; }
        [Required]
        public HierarchyId Node { get; set; }

        [ForeignKey(nameof(ParentId))]
        [InverseProperty(nameof(UserSubType.InverseParent))]
        public virtual UserSubType Parent { get; set; }
        [InverseProperty(nameof(UserSubType.Parent))]
        public virtual ICollection<UserSubType> InverseParent { get; set; }
        [InverseProperty(nameof(User.SubType))]
        public virtual ICollection<User> TblUsers { get; set; }
    }
}