// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using BuildingLink.ModuleServiceTemplate.Repositories.DatabaseFirst.SharedEntities;
using Microsoft.EntityFrameworkCore;

namespace BuildingLink.ModuleServiceTemplate.Repositories.DatabaseFirst.Users
{
    [Table("tblUser")]
    [Index(nameof(ParentUserId), Name = "IX_tblUser13")]
    [Index(nameof(FacilityId), Name = "IX_tblUser_20130923a")]
    [Index(nameof(Id), Name = "IX_tblUser_20130923b")]
    [Index(nameof(FacilityId), Name = "IX_tblUser_FacID")]
    [Index(nameof(Id), Name = "_dta_index_tblUser_14_1447168401__K1_2")]
    [Index(nameof(TypeId), nameof(ParentUserId), Name = "missing_index_14276_14275")]
    [Index(nameof(ProviderId), Name = "missing_index_2253_2252")]
    [Index(nameof(IsActive), nameof(SubTypeId), Name = "missing_index_9732_9731")]
    public partial class User
    {
        [Key]
        [Column("UserID")]
        public int Id { get; set; }
        [Column("FacID")]
        public int? FacilityId { get; set; }
        [Column("UnitID")]
        public int? UnitId { get; set; }
        [Column("TypeID")]
        public int TypeId { get; set; }
        [StringLength(100)]
        public string FirstName { get; set; }
        [Column("MidName")]
        [StringLength(100)]        
        public string MiddleName { get; set; }
        [Required]
        [StringLength(100)]
        public string LastName { get; set; }
        [Required]
        [StringLength(40)]
        public string UserName { get; set; }
        [Column("UserAct")]
        public bool IsActive { get; set; }
        public bool? ReadOnly { get; set; }
        [Column("CreateBy")]
        public int? CreatedByUserId { get; set; }
        [Column("LastChangeBy")]
        public int? LastChangedByUserId { get; set; }
        [StringLength(500)]
        public string HomePhone { get; set; }
        [StringLength(500)]
        public string CellPhone { get; set; }
        [StringLength(500)]
        public string WorkPhone { get; set; }
        [StringLength(500)]
        public string Email { get; set; }
        public int? ParentUserId { get; set; }
        public int? ProviderId { get; set; }
        [Column("ETLCreatedQueueId")]
        public int? EtlcreatedQueueId { get; set; }
        [Column("ETLMoveOutQueueId")]
        public int? EtlmoveOutQueueId { get; set; }
        public byte? PassportOverrideId { get; set; }
        public int? PasswordResetUserId { get; set; }
        public int SubTypeId { get; set; }
        public int? LoginInformationStatusId { get; set; }
        public int? BoardMemberTitleId { get; set; }

        [ForeignKey(nameof(CreatedByUserId))]
        public virtual User CreatedBy { get; set; }
        [InverseProperty(nameof(User.CreatedBy))]
        public virtual ICollection<User> InverseCreatedBy { get; set; }
        [ForeignKey(nameof(LastChangedByUserId))]
        public virtual User LastChanged { get; set; }
        [ForeignKey(nameof(ParentUserId))]
        public virtual User ParentUser { get; set; }
        [ForeignKey(nameof(PasswordResetUserId))]
        public virtual User PasswordResetUser { get; set; }
        [InverseProperty(nameof(User.PasswordResetUser))]
        public virtual ICollection<User> InversePasswordResetUser { get; set; }
        [InverseProperty(nameof(PermissionSetting.User))]
        public virtual ICollection<PermissionSetting> PermissionSettings { get; set; }
        [ForeignKey(nameof(SubTypeId))]
        public virtual UserSubType SubType { get; set; }
        [ForeignKey(nameof(UnitId))]
        public virtual Unit Unit { get; set; }
    }
}