// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BuildingLink.ModuleServiceTemplate.Repositories.DatabaseFirst.SharedEntities
{
    [Table("tblUnits")]
    [Index(nameof(IsActive), nameof(DeactivationDate), Name = "missing_index_753988")]
    [Index(nameof(FacilityId), nameof(IsActive), Name = "missing_index_764720")]
    public partial class Unit
    {
        [Key]
        [Column("UnitID")]
        public int Id { get; set; }
        [Column("PhysicalUnitID")]
        public int PhysicalUnitId { get; set; }
        [Column("FacID")]
        public int FacilityId { get; set; }
        [Column("CompFamName")]
        [Required]
        [StringLength(200)]
        public string CompanyOrFamilyName { get; set; }
        [Column("AltName")]
        [StringLength(1000)]
        public string AlternativeName { get; set; }
        [Column("AptLbl")]
        [StringLength(24)]
        public string ApartmentLabel { get; set; }
        [Column("AptID")]
        [StringLength(40)]
        public string ApartmentId { get; set; }
        [Column("UnitAct")]
        public bool IsActive { get; set; }
        [Column("UnitCreateBy")]
        public int? CreatedBy { get; set; }
        [Column("UnitCreate", TypeName = "datetime")]
        public DateTime? CreatedAt { get; set; }
        [Column("DeactDate", TypeName = "datetime")]
        public DateTime? DeactivationDate { get; set; }

        [ForeignKey(nameof(FacilityId))]
        public virtual Facility Facility { get; set; }
    }
}