// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BuildingLink.ModuleServiceTemplate.Repositories.DatabaseFirst.Users;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace BuildingLink.ModuleServiceTemplate.Repositories.DatabaseFirst.Data
{
    public partial class BuildingLinkContext
    {
        private BuildingLinkContextProcedures _procedures;

        public virtual BuildingLinkContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new BuildingLinkContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public BuildingLinkContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserPermissionSetting>().HasNoKey().ToView(null);
        }
    }

    public interface IBuildingLinkContextProcedures
    {
        Task<List<UserPermissionSetting>> GetUserPermissionSettingAsync(int? userId, int? permissionId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }

    public partial class BuildingLinkContextProcedures : IBuildingLinkContextProcedures
    {
        private readonly BuildingLinkContext _context;

        public BuildingLinkContextProcedures(BuildingLinkContext context)
        {
            _context = context;
        }

        public virtual async Task<List<UserPermissionSetting>> GetUserPermissionSettingAsync(int? userId, int? permissionId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "userId",
                    Value = userId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "permissionId",
                    Value = permissionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<UserPermissionSetting>("EXEC @returnValue = [dbo].[GetUserPermissionSetting] @userId, @permissionId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
